### ISSUE TITLE
Folder inside zip does not match build tag

### ISSUE THREAD

**Issue by se35710** [AdoptOpenJDK/openjdk8-nightly#9]
In the build with tag [jdk8u172-b00-20180430](https://github.com/AdoptOpenJDK/openjdk8-nightly/releases/tag/jdk8u172-b00-20180430) ([OpenJDK8_x64_Win_20180430.zip](https://github.com/AdoptOpenJDK/openjdk8-nightly/releases/download/jdk8u172-b00-20180430/OpenJDK8_x64_Win_20180430.zip)), the folder inside the zip archive is named `jdk8u172-b03`.

**Comment by karianna** [comment]
This issue was moved to AdoptOpenJDK/openjdk-build#484
